version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auto_eval
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -U user -d auto_eval -h localhost"]
     interval: 5s
     timeout: 5s
     retries: 5

  backend:
    build: ./auto-evaluation-back
    env_file:
      - ./auto-evaluation-back/.env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./auto-evaluation-app
    env_file:
      - ./auto-evaluation-app/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pg_data:
